#! /bin/sh
# Display byte size of files installed by a single or set of packages.
# For symlinks, the size of the symlink target path name is used.
set -e
trap "echo 'Failed!' >& 2" 0
for P
do
	dpkg -L "$P"
done | while IFS= read -r F
do
	if test -f "$F" || test -L "$F"
	then
		printf '%s\n' "$F"
	fi
done | xargs du --apparent-size -ch
trap - 0
