#! /bin/sh
set -e
tool=/opt/vc/bin/vcgencmd
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
test -f "$tool"
if test x"${0%-off}" != x"$0"
then
	power=0
	what=off
else
	power=1
	what=on
fi
echo "Switching display $what."
"$tool" display_power $power > /dev/null
