#! /bin/sh -e
if /etc/init.d/ntp status > /dev/null 2>& 1
then
	/etc/init.d/ntp stop
fi
echo "Trying to set time from Internet NTP servers..." >& 2
if ntpd -q -g -c /etc/ntp.conf
then
	/etc/init.d/fake-hwclock reload
	/etc/init.d/ntp start
fi
